import { KeySignature, LiturgicalSeason, LiturgicalYear } from "@/types/models";

export const liturgicalSeasonItems = [
    { label: "Advent", value: LiturgicalSeason.ADVENT },
    { label: "Christmas", value: LiturgicalSeason.CHRISTMAS },
    { label: "Ordinary Time", value: LiturgicalSeason.ORDINARY_TIME },
    { label: "Lent", value: LiturgicalSeason.LENT },
    { label: "Easter", value: LiturgicalSeason.EASTER },
    { label: "Pentecost", value: LiturgicalSeason.PENTECOST },
    { label: "Easter Triduum", value: LiturgicalSeason.TRIDUUM }
];

export const templateParts: Record<string, string[]> = {
    "sunday-mass": [
        "Entrance Hymn",
        "Kyrie",
        "Gloria",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Recessional Hymn",
    ],
    wedding: [
        "Prelude",
        "Processional",
        "Opening Hymn",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Recessional",
    ],
    ordination: [
        "Entrance Hymn",
        "Kyrie",
        "Gloria",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Litany of Saints",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Te Deum",
        "Recessional Hymn",
    ],
    funeral: [
        "Entrance Hymn",
        "Kyrie",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Song of Farewell",
        "Recessional Hymn",
    ],
    blank: [],
};

export const keySignatureItems: { label: string; value: KeySignature }[] = [
    { label: "C Major", value: KeySignature.C_MAJOR },
    { label: "G Major", value: KeySignature.G_MAJOR },
    { label: "D Major", value: KeySignature.D_MAJOR },
    { label: "A Major", value: KeySignature.A_MAJOR },
    { label: "E Major", value: KeySignature.E_MAJOR },
    { label: "B Major", value: KeySignature.B_MAJOR },
    { label: "F♯ Major", value: KeySignature.F_SHARP_MAJOR },
    { label: "C♯ Major", value: KeySignature.C_SHARP_MAJOR },
    { label: "F Major", value: KeySignature.F_MAJOR },
    { label: "B♭ Major", value: KeySignature.B_FLAT_MAJOR },
    { label: "E♭ Major", value: KeySignature.E_FLAT_MAJOR },
    { label: "A♭ Major", value: KeySignature.A_FLAT_MAJOR },
    { label: "D♭ Major", value: KeySignature.D_FLAT_MAJOR },
    { label: "G♭ Major", value: KeySignature.G_FLAT_MAJOR },
    { label: "C♭ Major", value: KeySignature.C_FLAT_MAJOR },

    { label: "A Minor", value: KeySignature.A_MINOR },
    { label: "E Minor", value: KeySignature.E_MINOR },
    { label: "B Minor", value: KeySignature.B_MINOR },
    { label: "F♯ Minor", value: KeySignature.F_SHARP_MINOR },
    { label: "C♯ Minor", value: KeySignature.C_SHARP_MINOR },
    { label: "G♯ Minor", value: KeySignature.G_SHARP_MINOR },
    { label: "D♯ Minor", value: KeySignature.D_SHARP_MINOR },
    { label: "A♯ Minor", value: KeySignature.A_SHARP_MINOR },
    { label: "D Minor", value: KeySignature.D_MINOR },
    { label: "G Minor", value: KeySignature.G_MINOR },
    { label: "C Minor", value: KeySignature.C_MINOR },
    { label: "F Minor", value: KeySignature.F_MINOR },
    { label: "B♭ Minor", value: KeySignature.B_FLAT_MINOR },
    { label: "E♭ Minor", value: KeySignature.E_FLAT_MINOR },
    { label: "A♭ Minor", value: KeySignature.A_FLAT_MINOR },
];

export const liturgicalYearItems = [
    { label: "Year A", value: LiturgicalYear.A },
    { label: "Year B", value: LiturgicalYear.B },
    { label: "Year C", value: LiturgicalYear.C },
]