export const keySignatures = [
    "C Major",
    "G Major",
    "D Major",
    "A Major",
    "E Major",
    "B Major",
    "F# Major",
    "Db Major",
    "Ab Major",
    "Eb Major",
    "Bb Major",
    "F Major",
    "A Minor",
    "E Minor",
    "B Minor",
    "F# Minor",
    "C# Minor",
    "G# Minor",
    "D# Minor",
    "Bb Minor",
    "F Minor",
    "C Minor",
    "G Minor",
    "D Minor",
];

export const liturgicalSeasons = [
    "Advent",
    "Christmas",
    "Ordinary Time",
    "Lent",
    "Easter",
    "Pentecost",
];

export const templateParts: Record<string, string[]> = {
    "sunday-mass": [
        "Entrance Hymn",
        "Kyrie",
        "Gloria",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Recessional Hymn",
    ],
    wedding: [
        "Prelude",
        "Processional",
        "Opening Hymn",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Recessional",
    ],
    ordination: [
        "Entrance Hymn",
        "Kyrie",
        "Gloria",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Litany of Saints",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Te Deum",
        "Recessional Hymn",
    ],
    funeral: [
        "Entrance Hymn",
        "Kyrie",
        "Responsorial Psalm",
        "Gospel Acclamation",
        "Offertory Hymn",
        "Sanctus",
        "Memorial Acclamation",
        "Great Amen",
        "Lamb of God",
        "Communion Hymn",
        "Song of Farewell",
        "Recessional Hymn",
    ],
    blank: [],
};