import { PDFDocument, PDFPage, StandardFonts, rgb } from "pdf-lib"
import { capitalize, formatDate, getLabelForValue } from "./utils"
import { keySignatureItems, liturgicalSeasonItems } from "./constants"

import { GenerateMassSelection } from "@/types/models"

export async function generateMassSelectionPDF(selection: GenerateMassSelection): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const pageWidth = 612
  const pageHeight = 792
  const margin = 50
  const footerHeight = 60

  const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBoldOblique)
  const headerFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

  const primaryColor = rgb(0, 0.77, 0.98) // #00c5fb (cyan)
  const textColor = rgb(0.2, 0.2, 0.2)
  const lightGray = rgb(0.95, 0.95, 0.95)
  const borderColor = rgb(0.9, 0.9, 0.9)
  const white = rgb(1, 1, 1)

  let currentPage = pdfDoc.addPage([pageWidth, pageHeight])
  let yPosition = pageHeight - margin

  const addFooterToPage = (page: PDFPage) => {
    const footerY = 25

    page.drawRectangle({
      x: 0,
      y: 0,
      width: pageWidth,
      height: footerY + 25,
      color: lightGray,
    })

    page.drawRectangle({
      x: 0,
      y: footerY + 23,
      width: pageWidth,
      height: 2,
      color: primaryColor,
    })

    const generatedText = `Generated by Ìpínayò • ${formatDate(new Date())}`

    page.drawText(generatedText, {
      x: margin,
      y: footerY,
      size: 8,
      font: bodyFont,
      color: rgb(0.5, 0.5, 0.5),
    })

    const creatorText = `Created by: ${selection.createdBy.name || selection.createdBy.email}`
    const creatorWidth = bodyFont.widthOfTextAtSize(creatorText, 8)

    page.drawText(creatorText, {
      x: pageWidth - creatorWidth - margin,
      y: footerY,
      size: 8,
      font: bodyFont,
      color: rgb(0.5, 0.5, 0.5),
    })
  }

  const checkNewPage = (requiredSpace: number) => {
    if (yPosition - requiredSpace < footerHeight + 20) {
      addFooterToPage(currentPage)
      currentPage = pdfDoc.addPage([pageWidth, pageHeight])
      yPosition = pageHeight - margin
      return true
    }
    return false
  }

  const titleLines = wrapText(selection.title, 50)
  const titleHeight = titleLines.length * 18
  checkNewPage(titleHeight + 10)

  const contentWidth = pageWidth - 2 * margin
  titleLines.forEach((line, idx) => {
    const textWidth = titleFont.widthOfTextAtSize(line, 16)
    const centeredX = margin + (contentWidth - textWidth) / 2
    currentPage.drawText(line, {
      x: centeredX,
      y: yPosition - idx * 18,
      size: 16,
      font: titleFont,
      color: textColor,
    })
  })

  yPosition -= titleHeight + 12

  const liturgicalInfoItems = [
    {
      label: "Date",
      value: formatDate(selection.date),
    },
    ...(selection.liturgicalYear ? [{ label: "Liturgical Year", value: `Year ${selection.liturgicalYear}` }] : []),
    ...(selection.liturgicalSeason ? [{
      label: "Season", value: getLabelForValue(
        liturgicalSeasonItems,
        selection.liturgicalSeason
      )
    }] : []),
    ...(selection.liturgy ? [{ label: "Liturgy", value: selection.liturgy }] : []),
    ...(selection.themes && selection.themes.length > 0
      ? [{ label: "Themes", value: selection.themes.map((t) => capitalize(t.name)).join(", ") }]
      : []),
    ...(selection.pastoralFocus ? [{ label: "Pastoral Focus", value: selection.pastoralFocus }] : []),
  ]

  checkNewPage(liturgicalInfoItems.length * 25 + 20)

  liturgicalInfoItems.forEach((item) => {
    // Label
    currentPage.drawText(item.label, {
      x: margin,
      y: yPosition,
      size: 9,
      font: headerFont,
      color: textColor,
    })

    // Value
    const valueLines = wrapText(item.value, 80)
    valueLines.forEach((line, idx) => {
      currentPage.drawText(line, {
        x: margin + 120,
        y: yPosition - idx * 12,
        size: 9,
        font: bodyFont,
        color: textColor,
      })
    })

    yPosition -= Math.max(20, valueLines.length * 12 + 5)
  })

  yPosition -= 1

  checkNewPage(50)

  const colPositions = [margin, margin + 120, margin + 280, margin + 380]

  currentPage.drawRectangle({
    x: margin - 5,
    y: yPosition - 25,
    width: pageWidth - 2 * margin + 10,
    height: 25,
    color: primaryColor,
  })

  const headers = ["Song Title", "Key", "Notes"]
  const headerPositions = [colPositions[1], colPositions[2], colPositions[3]]
  headers.forEach((header, index) => {
    currentPage.drawText(header, {
      x: headerPositions[index],
      y: yPosition - 15,
      size: 10,
      font: headerFont,
      color: white,
    })
  })

  yPosition -= 30

  selection.parts.forEach((part) => {
    // Calculate required height for this row
    const partNameLines = wrapText(part.partName, 18)
    const songTitleLines = wrapText(part.songTitle, 20)
    const notesLines = part.notes ? wrapText(part.notes, 15) : []
    const maxLines = Math.max(partNameLines.length, songTitleLines.length, notesLines.length, 1)
    const rowHeight = Math.max(40, maxLines * 12 + 10)

    checkNewPage(rowHeight + 10)

    currentPage.drawRectangle({
      x: margin - 5,
      y: yPosition - rowHeight,
      width: pageWidth - 2 * margin + 10,
      height: rowHeight,
      color: white,
      borderColor: borderColor,
      borderWidth: 0.5,
    })

    const verticalCenter = yPosition - rowHeight / 2

    // Part name - vertically centered
    partNameLines.forEach((line, lineIdx) => {
      const lineOffset = (partNameLines.length - 1) * 5.5
      currentPage.drawText(line, {
        x: colPositions[0],
        y: verticalCenter + lineOffset - lineIdx * 11,
        size: 9,
        font: headerFont,
        color: textColor,
      })
    })

    // Song title - vertically centered
    songTitleLines.forEach((line, lineIdx) => {
      const lineOffset = (songTitleLines.length - 1) * 5.5
      currentPage.drawText(line, {
        x: colPositions[1],
        y: verticalCenter + lineOffset - lineIdx * 11,
        size: 9,
        font: bodyFont,
        color: textColor,
      })
    })

    // Key signature - vertically centered
    if (part.keySignature) {
      currentPage.drawText(getLabelForValue(
        keySignatureItems,
        part.keySignature
      ).replace(/♭/g, 'b')
        .replace(/♯/g, '#'), {
        x: colPositions[2],
        y: verticalCenter,
        size: 9,
        font: bodyFont,
        color: textColor,
      })
    }

    // Notes - vertically centered
    if (part.notes) {
      notesLines.forEach((line, lineIdx) => {
        const lineOffset = (notesLines.length - 1) * 4
        currentPage.drawText(line, {
          x: colPositions[3],
          y: verticalCenter + lineOffset - lineIdx * 8,
          size: 8,
          font: bodyFont,
          color: textColor,
        })
      })
    }

    yPosition -= rowHeight
  })

  const pages = pdfDoc.getPages()
  pages.forEach((page) => {
    addFooterToPage(page)
  })

  return await pdfDoc.save()
}

function wrapText(text: string, maxCharsPerLine: number): string[] {
  const words = text.split(" ")
  const lines: string[] = []
  let currentLine = ""

  for (const word of words) {
    if ((currentLine + word).length <= maxCharsPerLine) {
      currentLine += (currentLine ? " " : "") + word
    } else {
      if (currentLine) {
        lines.push(currentLine)
      }
      currentLine = word
    }
  }

  if (currentLine) {
    lines.push(currentLine)
  }

  return lines
}
